#!/bin/bash

# node-adm module v0.1.0
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
#  $3 NTP	the NTP server address.
VERSION=0.1.0

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=ntp

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}
NTP=${3:-91.189.91.157:123}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo NTP: ${NTP}
echo

${NODECTL} ${NODE} "sudo sed -i -e 's/^#NTP=/NTP=${NTP}/' /etc/systemd/timesyncd.conf"

