#!/bin/bash

# node-adm module v0.1.0
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
VERSION=0.1.1

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=docker-config

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo

${NODECTL} ${NODE} "grep 'max-size' /etc/docker/daemon.json" \
	|| echo -e "${HC}${MODULENAME} check log FAIL${NC}"

${NODECTL} ${NODE} "grep 'bip' /etc/docker/daemon.json" \
	|| echo -e "${HC}${MODULENAME} check bip FAIL${NC}"

${NODECTL} ${NODE} "ip addr show dev docker0 | grep 192.168." \
	|| echo -e "${HC}${MODULENAME} check docker0 FAIL${NC}"
