#!/bin/bash

# node-adm module v0.1.0
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
VERSION=0.1.0

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=logrorate

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo

${NODECTL} ${NODE} "
sudo sed -i -e 's/^weekly/monthly/' /etc/logrotate.conf;
sudo sed -i -e 's/^rotate 4/rotate 60/' /etc/logrotate.conf;
sudo sed -i -e 's/^    monthly/    yearly/' /etc/logrotate.conf;
sudo sed -i -e 's/^    rotate 1/    rotate 5/' /etc/logrotate.conf;
sudo sed -i -e 's/rotate 7/rotate 60/' /etc/logrotate.d/rsyslog;
sudo sed -i -e 's/daily/monthly/' /etc/logrotate.d/rsyslog;
sudo sed -i -e 's/rotate 4/rotate 60/' /etc/logrotate.d/rsyslog;
sudo sed -i -e 's/weekly/monthly/' /etc/logrotate.d/rsyslog;
"

