#!/bin/bash

# node-adm module v0.1.0
#  usage: node-adm [module] [node] [module] ...
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
#  $3 HOSTFILE  where the hostfile to sync to node.
VERSION=0.1.0

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=logrorate

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo

${NODECTL} ${NODE} "grep '^monthly' /etc/logrotate.conf" \
	|| echo -e "${HC}${MODULENAME} check FAIL${NC}"
${NODECTL} ${NODE} "grep '^rotate 60' /etc/logrotate.conf" \
	|| echo -e "${HC}${MODULENAME} check FAIL${NC}"
${NODECTL} ${NODE} "grep '^[ \t]*yearly' /etc/logrotate.conf" \
	|| echo -e "${HC}${MODULENAME} check FAIL${NC}"
${NODECTL} ${NODE} "grep '^[ \t]*rotate 5' /etc/logrotate.conf" \
	|| echo -e "${HC}${MODULENAME} check FAIL${NC}"
${NODECTL} ${NODE} "grep 'monthly' /etc/logrotate.d/rsyslog" \
	|| echo -e "${HC}${MODULENAME} check FAIL${NC}"
${NODECTL} ${NODE} "grep 'rotate 60' /etc/logrotate.d/rsyslog" \
	|| echo -e "${HC}${MODULENAME} check FAIL${NC}"

