#!/bin/bash

# node-adm module v0.1.0
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
VERSION=0.1.0

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=kernel

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo

${NODECTL} ${NODE} "
grep -F 'linux-policy 1: increase UDP buffer' /etc/sysctl.conf || {
	echo '# linux-policy 1: increase UDP buffer' | sudo tee -a /etc/sysctl.conf ;
	echo 'net.core.rmem_max=26214400' | sudo tee -a /etc/sysctl.conf ;
	echo 'net.core.rmem_default=26214400' | sudo tee -a /etc/sysctl.conf ;
	sudo sysctl -p ;
} ;
"

