#!/bin/bash

# node-adm module v0.1.0
#  usage: node-adm [module] [node] [module] ...
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
#  $3 HOSTFILE  where the hostfile to sync to node.
VERSION=0.1.0

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=hosts

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}
HOSTFILE=${3:-/etc/hosts}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo HOSTFILE: ${HOSTFILE}
echo

echo "diff HOSTFILE:${HOSTFILE} | NODE HOSTFILE: ${NODE}:/etc/hosts"
cat ${HOSTFILE} | ${NODECTL} ${NODE} "diff -y --suppress-common-lines - /etc/hosts" \
	|| echo -e "${HC}${MODULENAME} check FAIL${NC}"

