#!/bin/bash

# node-adm module v0.1.0
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
VERSION=0.1.0

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=optimizer-kernel-network

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo

${NODECTL} ${NODE} "
grep -F 'NODE-ADM MODULE ${MODULENAME} 0: kernel network optimizer' /etc/sysctl.conf || {
	echo '# NODE-ADM MODULE ${MODULENAME} 0: kernel network optimizer' | sudo tee -a /etc/sysctl.conf ;
	echo 'net.core.somaxconn = 32768' | sudo tee -a /etc/sysctl.conf ;
	sudo sysctl -p ;
} ;
"

