#!/bin/bash

# node-adm module v0.1.0
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
#  $3 OPERATOR  the operator account of the node.
#  $4 MAILTO    the mail address of the operator.
VERSION=0.1.0

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=root-mail-alias

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}
OPERATOR=${3:-$(whoami)}
MAILTO=${4:-${OPERATOR}@localhost.localhost}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo OPERATOR: ${OPERATOR}
echo MAILTO: ${MAILTO}
echo

${NODECTL} ${NODE} "echo ${OPERATOR} | sudo tee /root/.forward ; echo ${MAILTO} > ~/.forward"

