#!/bin/bash

# node-adm module v0.1.0
#  usage: node-adm [module] [node] [module] ...
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
#  $3 HOSTFILE  where the hostfile to sync to node.
VERSION=0.1.0

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=root-mail-alias

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}
OPERATOR=${3:-$(whoami)}
MAILTO=${4:-${OPERATOR}@localhost.localhost}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo OPERATOR: ${OPERATOR}
echo MAILTO: ${MAILTO}
echo

[ "$(${NODECTL} ${NODE} "sudo cat /root/.forward")" == "${OPERATOR}" ] \
	|| echo -e "${HC}${MODULENAME} check 1 FAIL${NC}"

[ "$(${NODECTL} ${NODE} "cat \${HOME}/.forward")" == "${MAILTO}" ] \
	|| echo -e "${HC}${MODULENAME} check 2 FAIL${NC}"
