#!/bin/bash

# node-adm module v0.1.0
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
VERSION=0.1.0

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=hardware

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo

echo "Hostname: `hostname`"
echo "Date: `date`"

echo -e "${HC}$ lscpu${NC}"
lscpu

echo -e "${HC}$ lsmem${NC}"
lsmem

echo -e "${HC}$ lsblk (except loop devices)${NC}"
lsblk | grep -v loop

