#!/bin/bash

# node-adm module v0.1.0
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
VERSION=0.1.2

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=key-software

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo

echo -e "${HC}$ kernel version${NC}"
${NODECTL} ${NODE} "
	uname -r ;
	dpkg --get-selections | grep linux-image | grep '[^e]install$' ;
	dpkg --get-selections | grep linux-headers | grep '[^e]install$' ;
	dpkg --get-selections | grep linux-modules | grep '[^e]install$' ;
	"

echo -e "${HC}$ docker version${NC}"
${NODECTL} ${NODE} "
	docker version
	"

echo -e "${HC}$ ceph version${NC}"
${NODECTL} ${NODE} "
	sudo ceph version
	"

echo -e "${HC}$ kubernetes version${NC}"
${NODECTL} ${NODE} "
	kubelet version
	"
