#!/bin/bash

# node-adm module v0.1.0
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
#  $3 PROXY	the registry proxy address and port.
VERSION=0.1.0

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=registry-proxy

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}
PROXY=${3:-}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo PROXY: ${PROXY}
echo

if [ ! -z "${PROXY}" ]
then
	${NODECTL} ${NODE} "
		sudo jq '. + {\"registry-mirrors\": [\"${PROXY}\"]}' /etc/docker/daemon.json | sudo sponge /etc/docker/daemon.json ;
		sudo systemctl restart docker ;
		"
fi
