#!/bin/bash

# node-adm module v0.1.0
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
#  $3 HOSTPORT	the registry proxy address and port.
VERSION=0.1.0

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=registry-proxy

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}
HOSTPORT=${3:-}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo HOSTPORT: ${HOSTPORT}
echo

if [ ! -z "${HOSTPORT}" ]; then
	${NODECTL} ${NODE} "
		sudo mkdir -p /etc/docker/cert.d/${HOSTPORT} ;
		openssl s_client -connect ${HOSTPORT} -showcerts < /dev/null 2>/dev/null \
			| openssl x509 -outform PEM \
			| sudo tee /usr/local/share/ca-certificates/registry-proxy.crt \
			| sudo tee /etc/docker/cert.d/${HOSTPORT}/ca.crt ;
		sudo update-ca-certificates ;
		"

	${NODECTL} ${NODE} "
		sudo apt install moreutils jq -y ;
		"

	${NODECTL} ${NODE} "
		sudo jq '. + {\"registry-mirrors\": [\"https://${HOSTPORT}\"]}' /etc/docker/daemon.json | sudo sponge /etc/docker/daemon.json ;
		sudo systemctl restart docker ;
		"
fi
