#!/bin/bash

# node-adm module v0.1.0
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
#  $3 OPERATOR	the operator account of the node.
VERSION=0.1.1

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=docker

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}
OPERATOR=${3:$(whoami)}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo OPERATOR: ${OPERATOR}
echo

${NODECTL} ${NODE} "
	sudo apt install docker.io -y ;
	sudo apt-mark hold docker.io ;
	sudo systemctl enable docker ;
	sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf ;
	sudo usermod -a -G docker ${OPERATOR} ;
	"

