#!/bin/bash

# node-adm module v0.1.0
#  usage: node-adm [module] [node] [module] ...
# ARGUMENTS:
#  $1 NODECTL	the command to control node.
#  $2 NODE	which node to apply
#  $3 HOSTFILE  where the hostfile to sync to node.
VERSION=0.1.0

HC='\033[0;93m'
NC='\033[0m'

# module:
MODULENAME=sshd

# arguments:
NODECTL=${1:-ws ssh}
NODE=${2:-ws}
SECURE_PORT=${3:-22}

echo -e "${HC}=========================================================================${NC}"
echo -e "${HC}NODE-ADM MODULE: ${MODULENAME} ${VERSION}${NC}"
echo NODECTL: ${NODECTL}
echo NODE: ${NODE}
echo SECURE_PORT: ${SECURE_PORT}
echo

${NODECTL} ${NODE} "
sudo sed -i -e 's/^#Port 22/Port ${SECURE_PORT}/' /etc/ssh/sshd_config;
sudo sed -i -e 's/^#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config;
sudo sed -i -e 's/^#PubkeyAuthentication yes/AuthenticationMethods publickey\nPubkeyAuthentication yes/' /etc/ssh/sshd_config;
sudo sed -i -e 's/^#HostbasedAuthentication no/HostbasedAuthentication no/' /etc/ssh/sshd_config;
sudo sed -i -e 's/^#IgnoreUserKnownHosts no/IgnoreUserKnownHosts no/' /etc/ssh/sshd_config;
sudo sed -i -e 's/^#IgnoreRhosts yes/IgnoreRhosts yes/' /etc/ssh/sshd_config;
sudo sed -i -e 's/^#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config;
sudo sed -i -e 's/^#PermitEmptyPasswords no/PermitEmptyPasswords no/' /etc/ssh/sshd_config;
sudo sed -i -e 's/^#ClientAliveInterval 0/ClientAliveInterval 3600/' /etc/ssh/sshd_config;
sudo sed -i -e 's/^#ClientAliveCountMax 3/ClientAliveCountMax 0/' /etc/ssh/sshd_config;
"

